Repository Viindoo/odoo, pull requests merged in 2022-06, with the labels that each got.

#329 [FIX][15.0] web: calendar translate
  addons/web/static/src/legacy/js/views/calendar/calendar_renderer.js
Labels: :rocket: Running

#331 Merged from upstream 14 220601 01
  addons/account/models/account_move.py
  addons/calendar/models/calendar_attendee.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/http_routing/controllers/main.py
  addons/portal/controllers/portal.py
  addons/pos_hr/static/src/js/PaymentScreen.js
  addons/pos_hr/views/point_of_sale.xml
  addons/website/i18n/website.pot
  addons/website/models/website_snippet_filter.py
  addons/website_crm/models/crm_lead.py
  addons/website_forum/models/forum.py
  addons/website_sale/i18n/website_sale.pot
  doc/cla/individual/haumenphai.md
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: :rocket: Running

#327 [I18N][14.0] stock: retranslate module on 14.0
  addons/stock/i18n/vi.po
Labels: :rocket: Queue

#333 [FIX][14.0] microsoft_calendar: Bug when sync microsoft calendar
  addons/microsoft_calendar/tests/test_microsoft_service.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
Labels: :rocket: Running

#337 Merged from upstream 15 220602 01
  addons/account/views/account_move_views.xml
  addons/product/models/product_attribute.py
  addons/product_margin/models/product_product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/legacy/action_adapters.js
  addons/web/static/tests/webclient/actions/legacy_tests.js
Labels: :rocket: Running

#339 [I18N][14.0] hr_attendance: Edit translation
  addons/hr_attendance/i18n/vi.po
Labels: :rocket: Building

#321 [I18N] [14.0] Calendar: Translate some confusing words
  addons/calendar/i18n/vi.po
Labels: :rocket: Running

#336 [I18N][14.0]website_event,website_event_track:Translate wishlist field and start on Events
  addons/website_event/i18n/vi.po
  addons/website_event_track/i18n/vi.po
Labels: :rocket: Running

#343 Merged from upstream 14 220604 01
  addons/mrp/models/mrp_production.py
Labels: :rocket: Running

#342 Merged from upstream 13 220604 01
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
Labels: :rocket: Running

#344 Merged from upstream 15 220604 01
  addons/account/models/account_reconcile_model.py
  addons/google_calendar/models/google_credentials.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/models/mail_message.py
  addons/portal/tests/__init__.py
  addons/portal/tests/test_message_format_portal.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order_line.py
  addons/stock/views/stock_picking_views.xml
  addons/web/i18n/web.pot
  addons/web/static/src/webclient/user_menu/user_menu_items.js
  addons/web/static/tests/core/l10n/dates_tests.js
Labels: :rocket: Running

#352 Merged from upstream 13 220609 01
  addons/account/models/partner.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/http_routing/models/ir_http.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/sale/models/res_partner.py
  addons/sale/views/res_partner_views.xml
  odoo/addons/base/tests/test_mimetypes.py
Labels: :rocket: Running

#355 [I18N][15.0] maill: additional translation
  addons/mail/i18n/vi.po
Labels: :rocket: Running

#350 [I18N][14.0] purchase: retranslate the label of field
  addons/purchase/i18n/vi.po
Labels: :rocket: Building

#353 Merged from upstream 14 220609 01
  addons/account/models/account_reconcile_model.py
  addons/account/models/account_tax_report.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/http_routing/models/ir_http.py
  addons/l10n_es/data/account.account.template-common.csv
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/sale/models/sale.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/stock_account/report/report_stock_forecasted.py
  addons/test_website/tests/test_views_during_module_operation.py
  addons/website/models/ir_module_module.py
  addons/website/tests/test_views_inherit_module_update.py
  doc/cla/corporate/sygel.md
  odoo/addons/base/tests/test_mimetypes.py
Labels: :rocket: Running

#354 Merged from upstream 15 220609 01
  addons/account/models/account_move.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_account_move_reconcile.py
  addons/crm_mail_plugin/i18n/crm_mail_plugin.pot
  addons/crm_mail_plugin/static/src/to_translate/translations_gmail.xml
  addons/crm_mail_plugin/static/src/to_translate/translations_outlook.xml
  addons/event/models/event_registration.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/http_routing/models/ir_http.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi/tests/test_edi_json.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_pk/data/l10n_pk_chart_data.xml
  addons/l10n_tw/__manifest__.py
  addons/l10n_tw/data/l10n_tw_chart_data.xml
  addons/l10n_tw/demo/demo_company.xml
  addons/l10n_tw/static/description/icon.png
  addons/mail/controllers/mail.py
  addons/mail/wizard/mail_compose_message.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mrp/models/mrp_production.py
  addons/project/views/project_views.xml
  addons/project_mail_plugin/controllers/mail_plugin.py
  addons/project_mail_plugin/i18n/project_mail_plugin.pot
  addons/project_mail_plugin/static/src/to_translate/translations_gmail.xml
  addons/project_mail_plugin/static/src/to_translate/translations_outlook.xml
  addons/sale/models/sale_order.py
  addons/sales_team/models/crm_team.py
  addons/sales_team/tests/test_sales_team.py
  addons/stock_account/report/report_stock_forecasted.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_website/tests/test_views_during_module_operation.py
  addons/web/static/src/core/utils/scrolling.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/website/models/ir_module_module.py
  addons/website/tests/test_views_inherit_module_update.py
  addons/website_sale_delivery_mondialrelay/controllers/controllers.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_mimetypes.py
Labels: :rocket: Running

#357 Meged from upstream 13 220611 01
  addons/sale/i18n/sale.pot
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale_timesheet/models/product.py
Labels: :rocket: Running

#358 Meged from upstream 14 220611 01
  addons/hr_holidays/static/src/bugfix/bugfix.js
  addons/mail/static/src/components/activity/activity.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/widgets/form_renderer/form_renderer_tests.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/microsoft_calendar/tests/test_microsoft_service.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_epson_printer/static/src/js/printers.js
  addons/purchase/models/purchase.py
  addons/sale/i18n/sale.pot
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale_timesheet/models/product.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stock_valuation_layer_revaluation.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  odoo/tools/safe_eval.py
Labels: :rocket: Running

#349 [I18N][14.0] Calendar: Translate some confusing words
  addons/calendar/i18n/vi.po
Labels: :rocket: Running

#351 [FIX][14.0] hr_expense: fix error when click smart button 'Expenses' in sale order
  odoo/addons/base/models/ir_actions.py
Labels: :rocket: Running

#370 Merged from upstream 14 220622 01
  addons/account/models/account_move.py
  addons/board/controllers/main.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/security/hr_timesheet_security.xml
  addons/l10n_au/data/account_tax_template_data.xml
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_tracking_value.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/models/product_template.py
  addons/sale_mrp/models/sale.py
  addons/sale_timesheet/models/account.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock/models/stock_orderpoint.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_message_track.py
  addons/test_mass_mailing/models/__init__.py
  addons/test_mass_mailing/models/mailing_models_cornercase.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web_editor/static/src/js/editor/rte.js
  addons/website/models/mixins.py
  addons/website_event_track/views/event_track_templates_page.xml
  doc/cla/individual/grzana12.md
  odoo/addons/base/views/res_users_views.xml
Labels: :rocket: Building

#369 Merged from upstream 15 220622 01
  addons/board/controllers/main.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/common.py
  addons/crm/tests/test_crm_lead_multicompany.py
  addons/event_booth/data/event_booth_category_data.xml
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/wizard/account_payment_register.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/security/hr_timesheet_security.xml
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/__init__.py
  addons/mass_mailing/tests/test_mailing_retry.py
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/mass_mailing_sms/tests/__init__.py
  addons/mass_mailing_sms/tests/test_mailing_retry.py
  addons/portal/views/portal_templates.xml
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/purchase_requisition_stock_dropshipping/models/purchase.py
  addons/sale/models/product_template.py
  addons/sale_timesheet/report/project_profitability_report_analysis.py
  addons/sale_timesheet/tests/test_reporting.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_report.py
  addons/stock/views/stock_picking_views.xml
  addons/website/models/mixins.py
  addons/website/models/website.py
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/tests/test_base_url.py
  addons/website/tests/test_lang_url.py
  addons/website/tools.py
  addons/website/views/website_templates.xml
  addons/website_event_track/views/event_track_templates_page.xml
  addons/website_forum/static/src/js/website_forum.js
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/petrus-v.md
  odoo/addons/base/views/res_partner_views.xml
  odoo/addons/base/views/res_users_views.xml
Labels: :rocket: Building

#374 [I18N][14.0] website_forum: edit translation
  addons/website_forum/i18n/vi.po
Labels: :rocket: Running
