Repository Viindoo/odoo, pull requests merged in 2022-07, with the labels that each got.

#387 Merged from upstream 14 220705 02
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_template_data.xml
  addons/mail/static/src/components/activity/activity.js
  addons/mail/static/src/models/activity/activity.js
Labels: :rocket: Running

#367 [I18N][13.0] project: additional translation
  addons/project/i18n/vi.po
Labels: :rocket: Running

#398 [FIX] [15.0] hr_holidays: fix compute `_compute_from_holiday_status_id`
  addons/hr_holidays/models/hr_leave.py
Labels: :rocket: Running

#400 [I18N][14.0] project: modify translation due to recent update
  addons/project/i18n/vi.po
Labels: :rocket: Running

#412 [IMP][15.0] purchase: improve translation
  addons/purchase/i18n/vi.po
Labels: :rocket: Building

#409 [I18N][15.0] google_recaptcha: translate
  addons/google_recaptcha/i18n/vi.po
Labels: :rocket: Queue

#411 Merged from upstream 15 220721 01
  addons/account/views/account_move_views.xml
  addons/crm/views/crm_lead_views.xml
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/utils/google_calendar.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/product_matrix/models/product_template.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/sale_order_line.py
  addons/sale_management/models/sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/web/static/src/legacy/js/views/calendar/calendar_view.js
  addons/web/static/src/legacy/scss/fields.scss
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/xml/website_form_editor.xml
  addons/website_sale/models/product_product.py
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/tests/test_website_sale_cart.py
  addons/website_sale_stock_wishlist/views/templates.xml
  addons/website_slides/models/slide_slide.py
  doc/cla/individual/gordon.md
  odoo/addons/base/models/ir_fields.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/profiler.py
Labels: :rocket: Running

#416 Merged from upstream 15 220721 02
  addons/project/models/project.py
Labels: :rocket: Queue

#418 [I18N][15.0] project: adding translation
  addons/project/i18n/vi.po
Labels: :rocket: Building

#414 Merged from upstream 14 220721 01
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/crm/views/crm_lead_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: :rocket: Running

#417 [I18N][15.0] product,stock: add translation files
  addons/product/i18n/vi.po
  addons/stock/i18n/vi.po
Labels: :rocket: Running

#419 [I18N][15.0] gamification: update Vietnamese translation
  addons/gamification/i18n/vi.po
Labels: :rocket: Running

#423 [I18N] [14.0] mass_mailing : fix translate fields message_bounce
  addons/mass_mailing/i18n/vi.po
Labels: :rocket: Running

#393 [I18N][15.0] hr_holidays: Added translation for 'Time Off'
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Building

#426 [I18N][15.0] gamification: update translation
  addons/gamification/i18n/gamification.pot
Labels: :rocket: Building

#425 [I18N] project: fix translations
  addons/project/i18n/project.pot
  addons/project/i18n/vi.po
Labels: :rocket: Running

#424 Merged from upstream 15 220728 01
  addons/account/models/account_move.py
  addons/account/views/account_payment_view.xml
  addons/barcodes/models/barcode_nomenclature.py
  addons/barcodes/static/src/js/barcode_form_view.js
  addons/barcodes/static/tests/barcode_tests.js
  addons/barcodes/tests/test_barcode_nomenclature.py
  addons/hr_contract/i18n/hr_contract.pot
  addons/hr_contract/models/hr_contract_type.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_gcc_invoice_stock_account/__init__.py
  addons/l10n_gcc_invoice_stock_account/__manifest__.py
  addons/l10n_gcc_invoice_stock_account/views/report_invoice.xml
  addons/l10n_in/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/common.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/mrp/models/stock_orderpoint.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_procurement.py
  addons/mrp/views/stock_move_views.xml
  addons/payment/models/payment_transaction.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/project/static/src/js/project_kanban.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_create_picking.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_package_level.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/tests/test_packing.py
  addons/stock/wizard/stock_request_count.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/tests/test_get_current_website.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  doc/cla/corporate/allegro-it.md
  doc/cla/individual/lin-ww.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/addons/base/tests/test_reports.py
  odoo/tools/image.py
Labels: :rocket: Running

#428 [I18N][15.0] hr_holidays: Edit translation for 'Time Off'
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Running
