Repository Viindoo/odoo, pull requests merged in 2022-04, with the labels that each got.

#240 [FIX][I18N][14.0] Defination rank is Cấp Bậc for forum, website and Gamification
  addons/gamification/i18n/vi.po
  addons/website_forum/i18n/vi.po
  addons/website_profile/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#244 Merged from upstream 14 220401 02
  addons/account/models/account_move.py
  addons/auth_totp/controllers/home.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_es/data/account_tax_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
Labels: :rocket: Running

#246 Merged from upstream 13 220403 01
  .tx/config
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/i18n/fetchmail_outlook.pot
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/mrp_account/views/product_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/tests/test_image.py
  addons/website/tests/test_attachment.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/service/server.py
  odoo/tests/common.py
  odoo/tools/mail.py
Labels: :rocket: Running

#242 [FIX] [14.0] hr_expense: Fix expense view error
  addons/hr_expense/models/hr_expense.py
Labels: :rocket: Running

#239 [FIX][15.0] hr: Fix error when an internal user opens the department's list view
  addons/hr/models/hr_department.py
Labels: :rocket: Running

#250 Merged from upstream 14 220406 01
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_product_pricelist.py
Labels: :rocket: Queue

#251 [IMP] *: Correct Vietnamese translation for 'Fed. State'
  addons/base_address_city/i18n/vi.po
  addons/contacts/i18n/vi.po
  addons/crm/i18n/vi.po
  addons/crm/views/crm_lead_views.xml
  addons/hr/i18n/hr.pot
  addons/hr/i18n/vi.po
  addons/hr/views/res_users.xml
  addons/l10n_ar/report/invoice_report_view.xml
  addons/lunch/i18n/lunch.pot
  addons/lunch/i18n/vi.po
  addons/lunch/views/lunch_supplier_views.xml
  addons/payment/i18n/payment.pot
  addons/payment/i18n/vi.po
  addons/payment/models/payment_transaction.py
  addons/payment/views/payment_transaction_views.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/i18n/vi.po
  addons/point_of_sale/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml
  addons/pos_sale/i18n/vi.po
  addons/snailmail/i18n/vi.po
Labels: :rocket: Running

#256 Merged from upstream 13 220416 01
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_procurement.py
  addons/test_mail/tests/test_mail_message.py
  addons/website/models/assets.py
  addons/website/static/tests/tours/html_editor.js
  addons/website/tests/test_ui.py
  addons/website_forum/controllers/main.py
Labels: :rocket: Running

#257 [I18N] website: Update vi.po in i18n of module website in odoo13
  addons/website/i18n/vi.po
Labels: :rocket: Running

#258 [I18N] website: Update vi.po in i18n of module website in odoo14
  addons/website/i18n/vi.po
Labels: :rocket: Running

#260 Merged from upstream 15 220420 01
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ar/views/res_partner_view.xml
  addons/l10n_it_edi/models/res_partner.py
  addons/mail/models/models.py
  addons/mail/static/src/components/chat_window_manager/tests/chat_window_manager_tests.js
  addons/mail/static/src/components/message_list/message_list.js
  addons/mail/static/src/models/chat_window_manager/chat_window_manager.js
  addons/mrp/models/stock_orderpoint.py
  addons/mrp/tests/test_procurement.py
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/account_move.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_mrp/tests/__init__.py
  addons/sale_mrp/tests/test_sale_mrp_report.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_sale_stock_report.py
  addons/stock/models/product_strategy.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_generate_serial_numbers.py
  addons/stock/tests/test_packing.py
  addons/test_mail/tests/test_mail_message.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/js/menu/edit.js
  addons/website_forum/controllers/main.py
  addons/website_forum/models/forum.py
Labels: :rocket: Running

#259 Merged from upstream 14 220420 01
  addons/l10n_ar/views/res_partner_view.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/tests/test_procurement.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_message_post.py
  addons/website/models/assets.py
  addons/website/static/tests/tours/html_editor.js
  addons/website/tests/test_ui.py
  addons/website_forum/controllers/main.py
  addons/website_forum/models/forum.py
Labels: :rocket: Building, :warning: Failed

#262 Merged from upstream 13 220420 02
  addons/fetchmail/models/fetchmail.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/purchase/models/purchase.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/views/form_tests.js
  odoo/addons/base/models/res_users.py
Labels: :rocket: Running

#264 Merged from upstream 15 220420 02
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi_sale/__init__.py
  addons/l10n_fi_sale/__manifest__.py
  addons/l10n_fi_sale/i18n/fi.po
  addons/l10n_fi_sale/i18n/l10n_fi_sale.pot
  addons/l10n_fi_sale/models/__init__.py
  addons/l10n_fi_sale/models/sale.py
  addons/l10n_fi_sale/static/description/icon.png
  addons/l10n_it_edi_sdicoop/i18n_extra/l10n_it_edi_sdicoop.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_message_post.py
  odoo/addons/base/models/ir_attachment.py
Labels: :rocket: Running

#265 [FIX][15.0] web: remove duplicate lines
  addons/web/i18n/vi.po
Labels: :rocket: Running

#263 Merged from upstream 14 220420 02
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/sale_timesheet/views/hr_timesheet_templates.xml
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: :rocket: Running

#231 [FIX][14.0] purchase: Wrong statistics RFQs Sent Last 7 Days
  addons/purchase/models/purchase.py
Labels: :rocket: Running

#268 Merged from upstream 15 220422 01
  addons/account/models/product.py
  addons/crm_mail_plugin/controllers/mail_plugin.py
  addons/crm_mail_plugin/tests/__init__.py
  addons/crm_mail_plugin/tests/test_crm_mail_plugin.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_eg/data/account.account.template.csv
  addons/l10n_hk/data/account.account.template.csv
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_it_edi_sdicoop/tests/__init__.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mail/static/src/components/chat_window_manager/tests/chat_window_manager_tests.js
  addons/mail_plugin/tests/common.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_adyen/static/src/js/PaymentScreen.js
  addons/pos_adyen/static/src/js/models.js
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/project/static/src/js/widgets/project_name_with_subtask_count_widget.js
  addons/project/views/project_views.xml
  addons/project_mail_plugin/controllers/mail_plugin.py
  addons/purchase/tests/test_access_rights.py
  addons/sale/tests/test_onchange.py
  addons/sale_management/models/sale_order.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/survey/wizard/survey_invite.py
  addons/test_mass_mailing/tests/test_mailing_test.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/editor-test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/assets.py
  addons/website/security/ir.model.access.csv
  addons/website/static/tests/tours/html_editor.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_users.py
Labels: :rocket: Running

#266 Merged from upstream 13 220422 01
  addons/account/models/product.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mrp/models/mrp_document.py
  addons/sale/tests/test_onchange.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
  odoo/addons/base/models/ir_actions_report.py
Labels: :rocket: Running

#267 Merged from upstream 14 220422 01
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/tests/test_references.py
  addons/l10n_fi_sale/__init__.py
  addons/l10n_fi_sale/__manifest__.py
  addons/l10n_fi_sale/i18n/fi.po
  addons/l10n_fi_sale/i18n/l10n_fi_sale.pot
  addons/l10n_fi_sale/models/__init__.py
  addons/l10n_fi_sale/models/sale.py
  addons/l10n_fi_sale/static/description/icon.png
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_it_edi_sdicoop/tests/__init__.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mail/static/src/components/chat_window/chat_window.js
  addons/mail/static/src/components/chat_window/chat_window.xml
  addons/mail/static/src/components/chat_window_header/chat_window_header.js
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/payment/i18n/payment.pot
  addons/payment/models/__init__.py
  addons/payment/models/account_journal.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/purchase/tests/test_access_rights.py
  addons/sale/views/res_partner_views.xml
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
Labels: :rocket: Building, :warning: Failed

#276 [FIX][15.0] mail: remove the unescaped double quote
  addons/mail/i18n/vi.po
Labels: :rocket: Building

#275 [I18N][14.0] project: Translation privacy_visibility
  addons/project/i18n/vi.po
Labels: :rocket: Building

#274 Merged from upstream 15 220426 01
  addons/account/models/account_payment.py
  addons/event/models/event_event.py
  addons/project/controllers/portal.py
  addons/project/models/project.py
  addons/project/tests/test_task_dependencies.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_timesheet/report/project_profitability_report_analysis.py
  addons/sale_timesheet/tests/test_reporting.py
  addons/stock/models/stock_package_level.py
  addons/web/static/src/legacy/js/core/session.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/scss/modal.scss
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/product_views.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
Labels: :rocket: Running

#273 Merged from upstream 14 220426 01
  addons/account_edi/models/account_move.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/models/__init__.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/models/account_tax.py
  addons/account_edi_facturx/models/uom.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/google_calendar/models/res_users.py
  addons/microsoft_calendar/models/calendar.py
  addons/project/controllers/portal.py
  addons/sale/models/sale.py
  addons/web/static/src/js/core/session.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/product_views.xml
Labels: :rocket: Running

#272 Merged from upstream 13 220426 01
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/project/controllers/portal.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/tests/test_sale_pricelist.py
  addons/sale/views/sale_portal_templates.xml
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/wizard/sale_coupon_apply_code.py
  addons/web/static/src/js/core/session.js
  addons/website_sale_coupon/models/sale_order.py
Labels: :rocket: Running

#221 [FIX][14.0] hr_holidays: raise warning different timezone
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/migrations/14.0.1.6/pre-migration.py
  addons/hr_holidays/models/hr_leave.py
Labels: :rocket: Queue

#280 Merged from upstream 14 220419 01
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account_edi/data/cron.xml
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/fetchmail/models/fetchmail.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver.py
  addons/l10n_pt/__manifest__.py
  addons/l10n_pt/demo/demo_company.xml
  addons/mail/static/src/components/message/message.js
  addons/mail/static/src/components/notification_request/notification_request.xml
  addons/mail/tests/common.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_workcenter.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment/models/account_invoice.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductItem.js
  addons/point_of_sale/static/src/js/models.js
  addons/portal/i18n/portal.pot
  addons/portal/models/mail_message.py
  addons/portal/static/src/xml/portal_chatter.xml
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/product.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_coupon/tests/test_program_with_code_operations.py
  addons/sale_coupon/wizard/sale_coupon_apply_code.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_proc_rule.py
  addons/stock/tests/test_stock_flow.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
Labels: :rocket: Running

#279 Merged from upstream 13 220419 01
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/models/account_move.py
  addons/account_facturx/tests/test_facturx.py
  addons/event/models/event.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/drivers/KeyboardUSBDriver.py
  addons/l10n_ch/models/mail_template.py
  addons/product/models/product_attribute.py
  addons/product/models/product_template.py
  addons/product/tests/test_name.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/sale_coupon/tests/test_program_with_code_operations.py
  addons/sale_coupon/wizard/sale_coupon_apply_code.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/content/website_root.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
Labels: :rocket: Running
