Repository Viindoo/odoo, pull requests merged in 2022-10, with the labels that each got.

#546 Merged from upstream 15 221001 01
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/mrp/models/mrp_workorder.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/stock/views/stock_quant_views.xml
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/vvanneri-ia.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/tests/test_mail.py
Labels: :rocket: Running

#548 [I18N] [14.0] mass_mailing: Update translation file
  addons/mass_mailing/i18n/vi.po
Labels: :rocket: Building

#549 [FIX] stock_account: Add compute sudo to field access to model account move in stock inventory
  addons/stock_account/models/stock_inventory.py
Labels: :rocket: Running

#498 [FIX] [14.0] hr_timesheet: Adding translation
  addons/hr_timesheet/i18n/vi.po
Labels: :rocket: Building

#507 [I18N][15.0] hr_skill: Update vi.po translation file
  addons/hr_skills/i18n/vi.po
Labels: :rocket: Building

#515 [I18N][15.0] hr_recruitment: Fix double character & Edit sentence
  addons/account/i18n/vi.po
  addons/crm/i18n/vi.po
  addons/event/i18n/vi.po
  addons/event_booth/i18n/vi.po
  addons/fleet/i18n/vi.po
  addons/hr_contract/i18n/vi.po
  addons/hr_holidays/i18n/vi.po
  addons/hr_recruitment/i18n/vi.po
  addons/lunch/i18n/vi.po
  addons/mail/i18n/vi.po
  addons/maintenance/i18n/vi.po
  addons/mass_mailing/i18n/vi.po
  addons/mrp/i18n/vi.po
  addons/note/i18n/vi.po
  addons/point_of_sale/i18n/vi.po
  addons/product/i18n/vi.po
  addons/project/i18n/vi.po
  addons/purchase/i18n/vi.po
  addons/purchase_requisition/i18n/vi.po
  addons/repair/i18n/vi.po
  addons/sale/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/stock_landed_costs/i18n/vi.po
  addons/stock_picking_batch/i18n/vi.po
  addons/survey/i18n/vi.po
  addons/website_event_exhibitor/i18n/vi.po
  addons/website_event_track/i18n/vi.po
  addons/website_slides/i18n/vi.po
Labels: :rocket: Building

#561 [I18N][15.0] l10n_vn: edit translation of 1331 account name
  addons/l10n_vn/i18n_extra/vi_VN.po
Labels: :rocket: Running

#557 [I18N] [15.0] account: retranslation usererror
  addons/account/i18n/vi.po
Labels: :rocket: Running

#475 [I18N][15.0] stock: Add missing untranslated word
  addons/stock/i18n/vi.po
Labels: :rocket: Running

#568 Merged from upstream 15 221025 01
  addons/account/tests/common.py
  addons/base_import/tests/test_base_import.py
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_report.py
  addons/snailmail/models/snailmail_letter.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/web/static/src/legacy/js/views/kanban/kanban_model.js
  addons/web/static/src/legacy/js/views/sample_server.js
  addons/web/static/src/views/helpers/sample_server.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_tour/models/tour.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/views/templates.xml
Labels: :rocket: Running

#572 Merged from upstream 13 221027 01
  addons/snailmail/models/snailmail_letter.py
  addons/website_blog/controllers/main.py
  odoo/models.py
Labels: :rocket: Running

#571 Merged from upstream 15 221027 01
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_reconcile.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_uninstall.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_in/demo/product_demo.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_sa_invoice/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/l10n_uk/__manifest__.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_channel.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_channel.py
  addons/mail/tests/test_uninstall.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/product/data/product_demo.xml
  addons/purchase_stock/models/purchase.py
  addons/sale/data/product_product_demo.xml
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_stock/models/sale_order.py
  addons/stock/data/stock_demo.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock/views/stock_quant_views.xml
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/src/legacy/js/apps.js
  addons/web/static/src/legacy/js/components/action_menus.js
  addons/web/static/tests/legacy/core/py_utils_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/controllers/form.py
  addons/website/i18n/website.pot
  addons/website/models/assets.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/scss/secondary_variables.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/website_templates.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/models/slide_channel.py
  odoo/http.py
  odoo/models.py
  odoo/modules/registry.py
Labels: :rocket: Building, :warning: Failed

#573 [IMP][15.0] mail: Fix translation wrong
  addons/mail/i18n/vi.po
Labels: :rocket: Queue
