Repository Viindoo/odoo, pull requests merged in 2022-11, with the labels that each got.

#574 [I18N][15.0] account: improve translations
  addons/account/i18n/vi.po
Labels: :rocket: Queue

#563 [I18N][15.0] base: translate helpstring
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Running

#555 [I18N][14.0] hr_holidays: Translation error message
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Building

#588 Merged from upstream 13 221122 01
  addons/account/i18n/lt.po
  addons/account_facturx/i18n/ar.po
  addons/auth_oauth/i18n/ar.po
  addons/base_setup/i18n/ar.po
  addons/crm_iap_lead_website/i18n/ar.po
  addons/delivery/i18n/ar.po
  addons/fleet/i18n/ja.po
  addons/fleet/i18n/sr.po
  addons/gamification/i18n/ja.po
  addons/google_drive/i18n/ar.po
  addons/hr_attendance/i18n/ja.po
  addons/hr_gamification/i18n/ja.po
  addons/hr_holidays/i18n/ar.po
  addons/hr_maintenance/i18n/ja.po
  addons/hr_recruitment/i18n/ru.po
  addons/hr_recruitment_survey/i18n/ru.po
  addons/hr_skills/i18n/ja.po
  addons/hr_skills/i18n/ru.po
  addons/maintenance/i18n/ja.po
  addons/mrp/i18n/ar.po
  addons/mrp/i18n/it.po
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/purchase/i18n/nb.po
  addons/purchase_requisition/i18n/nb.po
  addons/sale_management/i18n/nb.po
  addons/sale_quotation_builder/i18n/et.po
  addons/sale_quotation_builder/i18n/nb.po
  addons/sale_timesheet/i18n/nb.po
  addons/stock/i18n/ar.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/stock/i18n/zh_CN.po
  addons/stock_account/i18n/ar.po
  addons/stock_picking_batch/i18n/ar.po
  addons/stock_sms/i18n/ar.po
  addons/survey/i18n/ru.po
  addons/utm/i18n/ar.po
  addons/web/i18n/it.po
  addons/web/i18n/ja.po
  addons/web_editor/i18n/ar.po
  addons/website/i18n/ar.po
  addons/website/i18n/ru.po
  addons/website_sale/i18n/it.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/nb.po
  addons/website_twitter/i18n/nb.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/hu.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/models/res_currency.py
Labels: :rocket: Running

#590 [MISC]ADD missing libs to requirements.txt
  requirements.txt
Labels: :rocket: Building, :warning: Failed

#520 [I18N][15.0] mrp* : improve vietnamese translation
  addons/mrp_account/i18n/vi.po
  addons/mrp_landed_costs/i18n/vi.po
  addons/mrp_product_expiry/i18n/vi.po
  addons/mrp_subcontracting/i18n/vi.po
Labels: :rocket: Running

#584 [IMP][15.0] point_of_sale: fix border overflow
  addons/point_of_sale/i18n/vi.po
Labels: :triangular_flag_on_post: Done
