Repository Viindoo/odoo, pull requests merged in 2022-08, with the labels that each got.

#430 [I18N][15.0] account: Edit translation for "account"
  addons/account/i18n/vi.po
Labels: :rocket: Running

#431 [IMP][15.0] product: Add translation
  addons/product/i18n/vi.po
Labels: :rocket: Building

#433 [FIX][15.0]sale: fix translation
  addons/sale/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#432 [FIX][14.0]sale: fix translation
  addons/sale/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#438 Merged from upstream 13 220807 01
  addons/google_gmail/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/website_twitter/views/res_config_settings_views.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/viindoo.md
Labels: :rocket: Running

#439 Merged from upstream 14 220807 01
  addons/account/models/account_move.py
  addons/account_qr_code_sepa/tests/test_sepa_qr.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  doc/cla/corporate/viindoo.md
Labels: :rocket: Running

#446 Merged from upstream 15 220812 01
  addons/account/models/account_full_reconcile.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_cl/models/account_move.py
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/__init__.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_coupon/static/src/js/tours/PosCoupon1.tour.js
  addons/pos_coupon/tests/test_frontend.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/sms/wizard/sms_composer.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_website/tests/test_fuzzy.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_event/__manifest__.py
  addons/website_event/static/src/snippets/s_country_events_list/000.scss
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: :rocket: Running

#451 Merged from upstream 15 220812 02
  addons/account/models/account_full_reconcile.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_cl/models/account_move.py
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/__init__.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_coupon/static/src/js/tours/PosCoupon1.tour.js
  addons/pos_coupon/tests/test_frontend.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/sms/wizard/sms_composer.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_website/tests/test_fuzzy.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_event/__manifest__.py
  addons/website_event/static/src/snippets/s_country_events_list/000.scss
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: :rocket: Running

#452 [I18N][15.0] hr_holidays: Improve translation file
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Running

#444 [I18N][15.0] account: additional translation
  addons/account/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#453 [I18N][15.0] web: update vi_VN translation file
  addons/web/i18n/vi.po
Labels: :rocket: Building

#454 [FIX][15.0] hr_holidays: fix bug there are 2 timeoffs in the same time
  addons/hr_holidays/models/hr_leave_type.py
Labels: :rocket: Running

#457 [I18N][15.0] purchase: update vi_VN translation file
  addons/purchase/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#463 [I18N][15.0] web: Update vi.po translation file
  addons/web/i18n/vi.po
Labels: :rocket: Running

#465 [I18N][15.0] purchase: Update vi.po translation file
  addons/account/i18n/vi.po
  addons/partner_autocomplete/i18n/vi.po
  addons/purchase/i18n/vi.po
  addons/purchase_requisition/i18n/vi.po
Labels: :rocket: Running

#466 [I18N][15.0] mail: Update vi.po translation file
  addons/mail/i18n/vi.po
Labels: :rocket: Running

#481 [I18N][15.0] base*: Update vi.po translation file
  addons/base_import/i18n/vi.po
  addons/event_booth/i18n/vi.po
  addons/gamification/i18n/vi.po
  addons/hr/i18n/vi.po
  addons/lunch/i18n/vi.po
  addons/mail/i18n/vi.po
  addons/mass_mailing/i18n/vi.po
  addons/mrp/i18n/vi.po
  addons/product/i18n/vi.po
  addons/sales_team/i18n/vi.po
  addons/web_editor/i18n/vi.po
  addons/website/i18n/vi.po
  addons/website_event_exhibitor/i18n/vi.po
  addons/website_forum/i18n/vi.po
  addons/website_sale/i18n/vi.po
  addons/website_slides/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Queue

#483 [I18N] l10n_vn: edit translation file for Vietnamese
  addons/l10n_vn/i18n_extra/vi_VN.po
Labels: :rocket: Queue

#482 [I18N][15.0] account*: Update vi.po translation file
  addons/account/i18n/vi.po
  addons/crm/i18n/vi.po
  addons/membership/i18n/vi.po
  addons/pos_sale/i18n/vi.po
  addons/sale/i18n/vi.po
  addons/website_crm/i18n/vi.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_sale/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Queue

#484 [I18N][15.0] base_setup: Viindoo debranding
  addons/base_setup/i18n/vi.po
Labels: :rocket: Running

#486 [I18N][15.0] calendar: Improve Vietnamese translations
  addons/calendar/i18n/vi.po
Labels: :rocket: Running

#478 [I18N][15.0] project, web: Add and improve translations
  addons/mail/i18n/vi.po
  addons/project/i18n/vi.po
  addons/purchase/i18n/vi.po
  addons/sale_timesheet/i18n/vi.po
  addons/web/i18n/vi.po
Labels: :rocket: Running

#485 [I18N][15.0] website_sale : update vietnamese translation
  addons/website_sale/i18n/vi.po
Labels: :rocket: Running

#489 [I18N][15.0] product: Update vi.po translation file
  addons/product/i18n/vi.po
  addons/purchase/i18n/vi.po
  addons/sale/i18n/vi.po
  addons/sale_project/i18n/vi.po
Labels: :rocket: Building

#487 [I18N][15.0] board: Updated Vietnamese translations
  addons/board/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#493 [I18N][15.0] contacts: Update vi.po translation file
  addons/contacts/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Running
