Repository Viindoo/odoo, pull requests merged in 2022-02, with the labels that each got.

#147 [I18N][15.0] project, hr: update translation
  addons/hr/i18n/vi.po
  addons/project/i18n/vi.po
Labels: :rocket: Building

#148 [I18N] hr_timesheet: Add missing translation
  addons/hr_timesheet/i18n/vi.po
Labels: :rocket: Running

#142 [I18N][14.0] product_expiry: retranslate on 14.0
  addons/product_expiry/i18n/vi.po
Labels: :rocket: Running

#151 Merged from upstream 13 220209 01
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/static/src/js/bank_statement.js
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_fiscal_position.py
  addons/account_facturx/data/facturx_templates.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_cl/models/res_partner.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_thread.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/payment_payulatam/views/payment_payulatam_templates.xml
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_attribute.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_coupon/models/sale_coupon.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/sale_coupon/tests/test_program_rules.py
  addons/sale_stock/models/stock.py
  addons/snailmail/models/snailmail_letter.py
  addons/stock_account/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  doc/cla/corporate/optesis.md
  doc/cla/individual/insiyashakir02.md
  odoo/models.py
Labels: :rocket: Running

#149 [I18N][14.0] Odoo: rename module odoo
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Running

#156 Merged from upstream 15 220210 01
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/mass_mailing/data/mailing_data_templates.xml
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_production_backorder.py
  addons/pad/py_etherpad/__init__.py
  addons/pos_sale/views/stock_template.xml
  addons/product/security/ir.model.access.csv
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_rules.py
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: :rocket: Running

#154 [I18N][14.0] translate: solving issues
  addons/mrp/i18n/vi.po
  addons/repair/i18n/vi.po
  addons/sale_stock/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/stock_account/i18n/vi.po
Labels: :rocket: Running

#155 [I18N][14.0] point_of_sale: translate Tip
  addons/point_of_sale/i18n/vi.po
Labels: :rocket: Running

#160 Merged from upstream 14 220212 01
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/crm/static/src/js/crm_form.js
  addons/crm/static/tests/tours/crm_email_and_phone_propagation.js
  addons/crm/tests/test_crm_ui.py
  addons/crm/views/assets.xml
  addons/google_spreadsheet/models/google_drive.py
  addons/http_routing/models/ir_http.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_production_backorder.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/snailmail/models/snailmail_letter.py
  addons/stock/models/stock_move_line.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/survey/controllers/main.py
  addons/web/static/src/js/core/domain.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/tests/core/domain_tests.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_form/static/src/snippets/s_website_form/options.js
  doc/cla/individual/SplashS.md
  doc/cla/individual/ppreeper.md
  odoo/addons/base/models/res_partner.py
  odoo/tests/common.py
Labels: :rocket: Running

#159 Merged from upstream 13 220212 01
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_reconciliation.py
  addons/google_spreadsheet/models/google_drive.py
  addons/http_routing/models/ir_http.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/product/models/product_template.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web/static/lib/Chart/Chart.js
  addons/web/static/src/scss/form_view.scss
  doc/cla/corporate/adhoc.md
  doc/cla/individual/SplashS.md
  doc/cla/individual/ppreeper.md
  odoo/tests/common.py
Labels: :rocket: Running

#161 [I18N] mail,hr,mass_mailing: add missing translations
  addons/hr/i18n/vi.po
  addons/mail/i18n/mail.pot
  addons/mail/i18n/vi.po
  addons/mass_mailing/i18n/vi.po
Labels: :rocket: Running

#162 [I18N] stock_add missing translate
  addons/stock/i18n/vi.po
Labels: :rocket: Queue

#164 V14 imp multilingual
  addons/account/i18n/vi.po
  addons/auth_totp/i18n/vi.po
  addons/auth_totp_portal/i18n/vi.po
  addons/crm/i18n/vi.po
  addons/delivery/i18n/delivery.pot
  addons/delivery/i18n/vi.po
  addons/delivery/models/delivery_grid.py
  addons/google_calendar/i18n/vi.po
  addons/hr_org_chart/i18n/vi.po
  addons/im_livechat/i18n/vi.po
  addons/point_of_sale/i18n/vi.po
  addons/sale/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/website_slides/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Running

#170 [I18N][14.0] sale_project: translate to vietnamese
  addons/sale_project/i18n/vi.po
  addons/sale_timesheet/i18n/vi.po
Labels: :rocket: Building

#174 [I18N][14.0] stock: correct transaltion
  addons/stock/i18n/vi.po
Labels: :rocket: Running

#175 Merged from upstream 14 220221 01
  addons/account/i18n/ca.po
  addons/account/i18n/es.po
  addons/account/i18n/et.po
  addons/account/i18n/it.po
  addons/account/i18n/nb.po
  addons/account/i18n/pl.po
  addons/account/i18n/sv.po
  addons/account/i18n/th.po
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/analytic/i18n/nb.po
  addons/auth_totp/i18n/es.po
  addons/auth_totp/i18n/sv.po
  addons/auth_totp_portal/i18n/es.po
  addons/base_setup/i18n/sv.po
  addons/calendar/i18n/it.po
  addons/contacts/i18n/nb.po
  addons/coupon/i18n/th.po
  addons/crm/i18n/it.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/es.po
  addons/delivery/i18n/it.po
  addons/delivery/i18n/th.po
  addons/digest/i18n/ar.po
  addons/event/i18n/sv.po
  addons/event/i18n/th.po
  addons/event_crm/i18n/es.po
  addons/l10n_ar/models/res_partner.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/mrp/models/stock_rule.py
  addons/website_sale/controllers/main.py
  doc/cla/corporate/forgeflow.md
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/i18n/sv.po
Labels: :rocket: Running

#176 [I18N][14.0] Landed cost: translate notebook title
  addons/stock_landed_costs/i18n/vi.po
Labels: :rocket: Running

#177 [I18N][13.0]sale_coupon: translation
  addons/sale_coupon/i18n/vi.po
Labels: :rocket: Running
