Repository Viindoo/odoo, pull requests merged in 2022-09, with the labels that each got.

#506 [I18N][15.0] hr_attendance: Update vi.po translation file
  addons/hr_attendance/i18n/vi.po
Labels: :rocket: Running

#500 [I18N][15.0] hr_expense: Update vi.po translation file
  addons/hr_expense/i18n/vi.po
Labels: :rocket: Running

#499 [I18N] mass_mailing: Update translation file
  addons/mass_mailing/i18n/vi.po
Labels: :rocket: Running

#505 [I18N][15.0] hr_recruitment: Update vi.po translation file
  addons/hr_recruitment/i18n/vi.po
Labels: :rocket: Queue

#503 [I18N][15.0] hr: Update vi.po translation file
  addons/hr/i18n/vi.po
Labels: :rocket: Queue

#525 [I18N][15.0] im_livechat : improve vietnamese translation
  addons/im_livechat/i18n/vi.po
  addons/mail/i18n/vi.po
Labels: :rocket: Running

#524 [I18N] [15.0] website_event: Adjust translation file
  addons/website_event/i18n/vi.po
Labels: :rocket: Running

#523 [I18N] [15.0] mass_mailing_sms: Adjust translation file
  addons/link_tracker/i18n/vi.po
  addons/mass_mailing/i18n/vi.po
  addons/mass_mailing_sms/i18n/vi.po
  addons/phone_validation/i18n/vi.po
Labels: :rocket: Running

#529 [I18N] [15.0] mass_mailing_sms: Adjust translation file
  addons/link_tracker/i18n/vi.po
  addons/mass_mailing/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#480 [I18N][15.0] point_of_sale: Update vi.po translation file
  addons/point_of_sale/i18n/vi.po
Labels: :rocket: Running

#492 [I18N][15.0] website_slide*: improve vietnamese translation
  addons/rating/i18n/vi.po
  addons/survey/i18n/vi.po
  addons/website_sale_slides/i18n/vi.po
  addons/website_slides/i18n/vi.po
  addons/website_slides_forum/i18n/vi.po
Labels: :rocket: Running

#522 [I18N] [15.0] mass_mailing: Adjust translation file
  addons/mass_mailing/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Building

#531 [I18N][15.0] *: Fix and improvements some problems
  addons/point_of_sale/i18n/vi.po
  addons/portal_rating/i18n/vi.po
  addons/website_forum/i18n/vi.po
  addons/website_slides/i18n/vi.po
Labels: :rocket: Queue

#533 Merged from upstream 15 220917 01
  addons/attachment_indexation/models/ir_attachment.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/models/__init__.py
  addons/l10n_ar_website_sale/models/ir_ui_view.py
  addons/l10n_bg/data/tax_report.xml
  addons/mrp/models/stock_rule.py
  odoo/addons/base/models/ir_attachment.py
  odoo/tests/test_module_operations.py
Labels: :rocket: Running

#476 [I18N][15.0] account: Add translation
  addons/account/i18n/vi.po
Labels: :rocket: Building

#534 [I18N] [15.0] account: Adjust translation vi.po file
  addons/account/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Running

#514 [I18N][15.0] website_hr_recruitment: improve vietnamese translation
  addons/website_hr_recruitment/i18n/vi.po
Labels: :rocket: Queue

#519 [I18N][15.0] maintenance : improve vietnamese translation
  addons/mail/i18n/vi.po
  addons/maintenance/i18n/vi.po
Labels: :rocket: Running

#539 Merged from upstream 15 220922 01
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/views/res_config_settings_views.xml
  addons/account/wizard/account_resequence.py
  addons/hr/data/hr_data.xml
  addons/l10n_in/__manifest__.py
  addons/l10n_in/views/account_journal_views.xml
  addons/l10n_in/views/res_company_view.xml
  addons/l10n_in/views/res_country_state_view.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/post_processing.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_gift_card/i18n/pos_gift_card.pot
  addons/pos_gift_card/static/src/js/models.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale_margin/__init__.py
  addons/pos_sale_margin/__manifest__.py
  addons/pos_sale_margin/report/__init__.py
  addons/pos_sale_margin/report/sale_report.py
  addons/pos_sale_margin/tests/__init__.py
  addons/pos_sale_margin/tests/test_pos_sale_margin_report.py
  addons/product_expiry/models/stock_move_line.py
  addons/product_expiry/tests/test_stock_production_lot.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/payment_transaction.py
  addons/sale/models/res_partner.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web/tests/test_base_document_layout.py
  addons/web_editor/controllers/main.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_currency.py
  setup/win32/Makefile
Labels: :rocket: Running

#538 Merged from upstream 13 220922 01
  addons/account/i18n/ar.po
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/tr.po
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/hr.po
  addons/digest/i18n/hu.po
  addons/hr_attendance/i18n/ja.po
  addons/hr_expense/i18n/ja.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_skills/i18n/mn.po
  addons/hr_timesheet/i18n/lt.po
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_in/views/report_invoice.xml
  addons/mail/i18n/he.po
  addons/mail/i18n/mn.po
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_workorder_operation.py
  addons/payment/i18n/mn.po
  addons/payment/static/src/js/payment_processing.js
  addons/payment_alipay/i18n/mn.po
  addons/payment_paypal/i18n/mn.po
  addons/point_of_sale/i18n/fi.po
  addons/portal/i18n/mn.po
  addons/pos_cash_rounding/i18n/fi.po
  addons/product/i18n/hr.po
  addons/product/i18n/mn.po
  addons/project/i18n/ar.po
  addons/repair/i18n/ja.po
  addons/sale/i18n/ar.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/mn.po
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_margin/models/sale_order.py
  addons/sale_product_configurator/i18n/hr.po
  addons/sale_stock/models/account_move.py
  addons/stock/i18n/hr.po
  addons/stock/i18n/mn.po
  addons/stock_account/models/stock_inventory.py
  addons/website/i18n/fr.po
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_blog/i18n/he.po
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates.xml
  addons/website_forum/i18n/mn.po
  addons/website_sale/i18n/mn.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/it.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/pl.po
Labels: :rocket: Building, :warning: Failed

#541 Merged from upstream 15 220924 01
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_notifications.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_eu_oss/models/eu_tag_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_account/models/product.py
  addons/sale/models/sale_order_line.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/website_templates.xml
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/data/res.country.state.csv
Labels: :rocket: Queue

#542 [I18N][15.0] stock: Add translation
  addons/stock/i18n/vi.po
Labels: :rocket: Queue
