Repository Viindoo/odoo, pull requests merged in 2022-03, with the labels that each got.

#179 [I18N][14.0] sale_stock: add missing translate
  addons/sale_stock/i18n/vi.po
Labels: :rocket: Running

#182 Merged from upstream 14 220303 01
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/repair/models/repair.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/models/website.py
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/tools/cloc.py
Labels: :rocket: Running

#184 Merged from upstream 13 220308 01
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_move_views.xml
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/delivery/models/delivery_grid.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/lunch/controllers/main.py
  addons/mail/models/mail_channel.py
  addons/mrp/models/product.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_views.xml
  odoo/addons/base/tests/test_cloc.py
  odoo/models.py
  odoo/tests/common.py
  odoo/tools/cloc.py
Labels: :rocket: Running

#183 [FIX][14.0] mail: error when reading name of private channel
  addons/mail/controllers/main.py
  addons/mail/models/mail_followers.py
  addons/mail/models/mail_thread.py
Labels: :rocket: Running

#187 [I18N][14.0] hr: correct translation
  addons/hr/i18n/vi.po
Labels: :rocket: Running

#190 Merged from upstream 13 220311 01
  addons/account/models/account_move.py
  addons/l10n_ar/models/res_partner.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/discuss.js
  addons/payment_sips/models/payment.py
  setup/package.py
Labels: :rocket: Running

#194 [I18n][14.0] mail: update activity tranlation
  addons/mail/i18n/vi.po
Labels: :rocket: Building

#191 Merged from upstream 14 220311 01
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/base_vat/models/res_partner.py
  addons/hr/models/res_users.py
  addons/hr/tests/test_self_user_access.py
  addons/hr/views/res_users.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/payment_sips/models/payment.py
  addons/purchase_stock/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/survey/controllers/main.py
Labels: :rocket: Running

#193 [FIX][I18N][14.0] Thay đổi dịch thuật huy chương sang huy hiệu để đồng bộ
  addons/hr_gamification/i18n/vi.po
  addons/survey/i18n/vi.po
  addons/web/i18n/vi.po
  addons/website_forum/i18n/vi.po
  addons/website_profile/i18n/vi.po
  addons/website_slides/i18n/vi.po
Labels: :rocket: Running

#196 Merged from upstream 14 220312 01
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  addons/payment/static/lib/jquery.payment/jquery.payment.js
  addons/sale_margin/views/sale_margin_view.xml
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: :rocket: Running

#195 Merged from upstream 13 220312 01
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: :rocket: Running

#198 [I18N][14.0] purchase: vietnamese translation
  addons/purchase/i18n/vi.po
Labels: :rocket: Running

#210 [I18N][14.0] maintenance: translate requests
  addons/maintenance/i18n/vi.po
Labels: :rocket: Running

#212 Merged from upstream 14 220320 01
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/sv.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account_edi/i18n/de.po
  addons/account_edi/i18n/es.po
  addons/account_edi/i18n/uk.po
  addons/account_payment/i18n/sk.po
  addons/adyen_platforms/i18n/it.po
  addons/board/i18n/sv.po
  addons/calendar_sms/i18n/he.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/he.po
  addons/crm_iap_lead_enrich/i18n/it.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/event/i18n/fr.po
  addons/event/i18n/th.po
  addons/event_crm/i18n/th.po
  addons/event_sale/i18n/th.po
  addons/event_sms/i18n/th.po
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/payment_ingenico/data/payment_acquirer_data.xml
  addons/payment_ingenico/models/payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/sale.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web_editor/controllers/main.py
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/he.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/sv.po
  odoo/addons/base/i18n/th.po
Labels: :rocket: Building, :warning: Failed

#213 [I18N] *: add missing translations
  addons/account_lock/i18n/vi.po
  addons/auth_signup/i18n/vi.po
Labels: :rocket: Running

#199 [I18N][14.0] account: Incoterms Vietnamese translation
  addons/account/i18n/vi.po
Labels: :rocket: Running

#207 [FIX][14.0]account: account admin can't Add a Bank Account
  addons/account/views/res_partner_bank_views.xml
Labels: :rocket: Running

#208 [FIX][14.0]website_forum: fix shallow copy obj
  addons/website_forum/models/forum.py
Labels: :rocket: Running

#216 Merged from upstream 13 220323 01
  addons/auth_ldap/models/res_company_ldap.py
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_document.py
  addons/mrp/models/mrp_production.py
  addons/payment_ingenico/data/payment_acquirer_data.xml
  addons/payment_ingenico/models/payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/purchase_mrp/i18n/purchase_mrp.pot
  addons/purchase_mrp/models/stock_move.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/report/picking_templates.xml
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/website_sale/models/crm_team.py
  addons/website_sale/views/sale_report_views.xml
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
Labels: :rocket: Running

#220 [FIX][14.0] mail_thread: fix unlink mail.message
  addons/mail/models/mail_thread.py
Labels: :rocket: Building, :warning: Failed

#227 [I18N][14.0] hr_expense: translation
  addons/hr_expense/i18n/vi.po
Labels: :rocket: Queue

#229 [FIX][14.0] New compute and stored Many2many field is not computed
  odoo/fields.py
Labels: :rocket: Running

#233 [I18N][14.0] Inventory: add missing translation
  addons/stock/i18n/vi.po
Labels: :rocket: Building

#230 Merged from upstream 14 220329 01
  addons/account/i18n/ca.po
  addons/account/i18n/et.po
  addons/account/i18n/hr.po
  addons/account/i18n/it.po
  addons/account/i18n/nb.po
  addons/account/i18n/sv.po
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/wizard/account_resequence.py
  addons/account_edi/i18n/it.po
  addons/account_edi/i18n/th.po
  addons/account_edi_facturx/i18n/es_MX.po
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_payment/i18n/lv.po
  addons/auth_oauth/i18n/th.po
  addons/auth_password_policy/i18n/th.po
  addons/auth_signup/i18n/th.po
  addons/auth_signup/i18n/vi.po
  addons/auth_totp/i18n/th.po
  addons/calendar/i18n/ca.po
  addons/calendar/i18n/fr.po
  addons/calendar/i18n/it.po
  addons/crm/i18n/ca.po
  addons/crm/i18n/hr.po
  addons/crm/i18n/sv.po
  addons/crm_iap_lead_enrich/i18n/ar.po
  addons/digest/i18n/et.po
  addons/digest/i18n/hr.po
  addons/event/i18n/ca.po
  addons/event_crm/i18n/es.po
  addons/fetchmail/i18n/et.po
  addons/hr_timesheet/controllers/portal.py
  addons/im_livechat/static/src/legacy/public_livechat.js
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/web/controllers/main.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/control_panel/search_bar.js
  addons/web/static/tests/control_panel/search_bar_tests.js
  addons/website_livechat/static/src/legacy/public_livechat.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/i18n/th.po
Labels: :rocket: Running

#235 Merged from upstream 14 220330 01
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_cancel_mo.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/sale/models/sale.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/sale_mrp/models/sale.py
  addons/website_crm/models/crm_lead.py
  odoo/addons/base/data/res.country.state.csv
Labels: :rocket: Running

#228 [I18N][14.0]hr_skills_survey: Update translate file
  addons/hr_skills_survey/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#237 Merged from upstream 14 220331 01
  .tx/config
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/i18n/fetchmail_outlook.pot
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_calendar/models/calendar.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/mrp_account/views/product_views.xml
  addons/mrp_landed_costs/models/stock_landed_cost.py
  addons/mrp_landed_costs/tests/test_stock_landed_costs_mrp.py
  addons/mrp_landed_costs/views/stock_landed_cost_views.xml
  addons/sale_timesheet/models/project_overview.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
Labels: :rocket: Building
