Repository Viindoo/odoo, pull requests merged in 2023-09, with the labels that each got.

#755 Merge upstream to viindoo 20230914 01
  addons/account/models/account_move_line.py
  addons/account/models/account_payment_method.py
  addons/account/views/report_invoice.xml
  addons/event/controllers/main.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/mail/models/mail_composer_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users_settings.py
  addons/mail/static/src/models/composer_view.js
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/portal/static/src/scss/portal.scss
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_order_cancel.py
  addons/sale/wizard/sale_order_cancel.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/controllers/utils.py
  addons/web/static/src/views/fields/binary/binary_field.xml
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_popup/001.scss
  addons/website/static/tests/tours/link_tools.js
  addons/website/tests/test_menu.py
  addons/website_sale/models/product_template.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_related_translation.py
  odoo/models.py
  odoo/tools/translate.py
Labels: :rocket: Running

#758 [16.0][i18n] crm: imp translation
  addons/crm/i18n/vi.po
Labels: :rocket: Running

#760 Merge from upstream 13 230918 01
  odoo/addons/base/models/ir_module.py
Labels: :rocket: Running

#765 Merged from upstream 14 230921 01
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/bus/models/bus.py
  addons/l10n_it/data/report_invoice.xml
  addons/l10n_mx/models/chart_template.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website/static/src/js/content/snippets.animation.js
  doc/cla/corporate/ibm.md
Labels: :rocket: Running

#766 Merged from upstream 15 230921 01
  addons/hr_holidays/report/hr_leave_employee_type_report.py
  addons/l10n_it/data/report_invoice.xml
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_procurement.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/legacy/js/core/menu.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/website.py
  addons/website/static/src/js/content/menu.js
  doc/cla/corporate/ibm.md
Labels: :rocket: Running

#753 [16.0][i18n] mail: add translate in mail call settings
  addons/mail/i18n/vi.po
Labels: :warning: Failed

#769 [16.0][I18N] mail: add vie translate for call settings
  addons/mail/i18n/vi.po
Labels: :warning: Failed

#756 [16.0][i18n] survey: add more vie translation
  addons/survey/i18n/vi.po
Labels: :rocket: Queue

#774 Merged from upstream 16 230929 01
  addons/account/models/account_account.py
  addons/account/models/partner.py
  addons/account/wizard/account_invoice_send.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_payment/controllers/portal.py
  addons/base_vat/models/res_partner.py
  addons/fleet/report/fleet_report.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_timesheet/views/project_views.xml
  addons/iap/models/iap_account.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mail/static/src/models/blur_manager.js
  addons/mail/static/tests/qunit_suite_tests/models/file_uploader_tests.js
  addons/microsoft_account/models/microsoft_service.py
  addons/payment/static/src/xml/payment_post_processing.xml
  addons/point_of_sale/models/account_bank_statement.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/db.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_loyalty/models/pos_session.py
  addons/project/models/project.py
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_lot.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/__manifest__.py
  addons/web/static/tests/utils.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/snippets/s_share/000.js
  addons/website/static/src/snippets/s_table_of_content/options.js
  addons/website_blog/static/src/js/options.js
  addons/website_slides/views/website_slides_templates_lesson.xml
  doc/cla/corporate/abilium.md
  odoo/addons/base/data/res.lang.csv
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/tests/_odoo_checker_markup.py
  odoo/tests/test_security.py
  odoo/tools/translate.py
Labels: :rocket: Running
