Repository Viindoo/odoo, pull requests merged in 2023-03, with the labels that each got.

#641 Merged from upstream 13 230308 01
  addons/auth_oauth/i18n/vi.po
  addons/snailmail/models/snailmail_letter.py
Labels: :rocket: Running

#632 [I18N][15.0] stock_landed_costs: fix translate file
  addons/stock_landed_costs/i18n/vi.po
Labels: :triangular_flag_on_post: Done

#646 Merged from upstream 15 230315 01
  addons/account/views/account_reconcile_model_views.xml
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/hr/models/mail_channel.py
  addons/mail/data/mail_templates.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website_slides/static/src/scss/website_slides.scss
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: :warning: Failed

#647 Merged from upstream 14 230318 01
  addons/account/models/account_reconcile_model.py
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/event/controllers/main.py
  addons/mail/data/mail_data.xml
  addons/mail_client_extension/views/mail_client_extension_login.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/views/product_views.xml
  addons/stock/wizard/stock_picking_return.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_snippets.py
  addons/website/views/assets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: :rocket: Running

#648 Merged from upstream 15 230318 01
  addons/account/models/account_journal.py
  addons/account/models/account_reconcile_model.py
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_edi/tests/common.py
  addons/event/controllers/main.py
  addons/mail/controllers/discuss.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/mail_plugin/views/mail_plugin_login.xml
  addons/mrp/models/mrp_unbuild.py
  addons/payment/utils.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_project/models/sale_order.py
  addons/sale_stock/tests/test_report.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_stock/tests/test_sale_stock_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/product_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock/wizard/stock_picking_return.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/models/account_move.py
  addons/survey/views/survey_report_templates.xml
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_ir_cron.py
Labels: :rocket: Running
