Repository Viindoo/odoo, pull requests merged in 2023-06, with the labels that each got.

#686 Merged from upstream 14 230602 01
  addons/account_edi/models/__init__.py
  addons/account_edi/models/uom.py
  addons/account_edi_facturx/models/__init__.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/translation_dialog.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  addons/website_crm/views/website_crm_templates.xml
  addons/website_form/views/website_form_templates.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_test_suite.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/modules/loading.py
  odoo/service/server.py
  odoo/tests/common.py
  odoo/tests/loader.py
Labels: :rocket: Running

#685 Merged from upstream 15 230602 01
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/crm/tests/test_performances.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mail/models/mail_thread.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  addons/website/tests/test_page.py
  addons/website_payment/static/src/snippets/s_donation/000.js
  addons/website_sale_stock_wishlist/views/templates.xml
  odoo/addons/base/wizard/base_import_language.py
Labels: :warning: Failed

#687 [I18N][15.0] mrp: update translate
  addons/mrp/i18n/vi.po
Labels: :rocket: Queue

#688 Merged from upstream 13 230607 01
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
Labels: :warning: Failed

#693 [I18N][15.0] mrp: update translation
  addons/mrp/i18n/vi.po
Labels: :rocket: Running

#694 Merged from upstream 14 230609 01
  addons/l10n_cl/models/account_move.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/point_of_sale/models/account_tax.py
  addons/survey/views/survey_templates.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: :rocket: Running

#695 Merged from upstream 15 230609 01
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/point_of_sale/models/account_tax.py
  addons/stock/models/stock_move.py
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_result.html
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/modules/registry.py
  odoo/osv/expression.py
Labels: :rocket: Running

#697 [I18N][15.0] mrp, account: Update field labels
  addons/account/i18n/vi.po
  addons/mrp/i18n/vi.po
Labels: :rocket: Queue

#701 [I18N] [15.0] account: update translate
  addons/account/i18n/vi.po
Labels: :rocket: Building

#702 Merged from upstream 14 230615 01
  addons/l10n_ch/models/mail_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/models/hr_recruitment.py
Labels: :rocket: Running

#703 Merged from upstream 15 230615 01
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mrp_account/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
Labels: :rocket: Running

#704 Merged from upstream 16 230615 01
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/tests/tours/tax_group_tests.js
  addons/account/tests/test_tour.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_picking.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website_slides/controllers/main.py
  odoo/models.py
Labels: :rocket: Running

#705 Merged from upstream 15 20230616
  addons/account/models/company.py
  addons/account/views/account_analytic_default_view.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/event/i18n/event.pot
  addons/event/models/event_mail.py
  addons/event_booth/models/event_booth_category.py
  addons/event_sms/models/event_mail.py
  addons/gamification/models/badge.py
  addons/hr/models/hr_job.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/payment/models/payment_transaction.py
  addons/point_of_sale/models/account_journal.py
  addons/point_of_sale/models/pos_order.py
  addons/project/models/project.py
  addons/sale/models/account_move_line.py
  addons/test_event_full/tests/__init__.py
  addons/test_event_full/tests/test_event_mail.py
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/test/editor-test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_result.html
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_event_track/models/event_track.py
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/models/hr_recruitment.py
  addons/website_slides/models/res_partner.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/__init__.py
  addons/website_slides/tests/test_attendee.py
Labels: :rocket: Running

#706 [I18N] account: update translate
  addons/account/i18n/vi.po
Labels: :rocket: Queue
