Repository Viindoo/odoo, pull requests merged in 2023-04, with the labels that each got.

#653 Merged from upstream 14 230403 01
  addons/account/controllers/portal.py
  addons/account/models/chart_template.py
  addons/account/security/account_security.xml
  addons/account/tests/test_chart_template.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/coupon/models/coupon_program.py
  addons/google_recaptcha/static/src/js/recaptcha.js
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hw_drivers/controllers/driver.py
  addons/hw_drivers/driver.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_ph/models/res_partner.py
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/js/db.js
  addons/portal/static/src/scss/portal.scss
  addons/purchase_stock/models/purchase.py
  addons/sale/report/sale_report_views.xml
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/report/stock_report_deliveryslip.xml
  addons/stock/i18n/stock.pot
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/stock/views/stock_package_level_views.xml
  addons/stock/wizard/product_replenish.py
  addons/survey/views/survey_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/js/website_blog.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_profile/views/website_profile.xml
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_slides/static/src/js/slides_course_join.js
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_twitter/static/src/js/website.twitter.animation.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/tranngocson1996.md
  odoo/addons/base/models/res_partner.py
Labels: :rocket: Running

#655 [MISC] *: update requirement for feature stable and to avoid warning
  requirements.txt
Labels: :warning: Failed

#657 [I18N][16.0] point_of_sale: Upgrade i18n for module point_of_sale
  addons/point_of_sale/i18n/vi.po
Labels: :rocket: Building

#656 [I18N] [16.0] pos_*: improve translation vi
  addons/account/i18n/vi.po
  addons/loyalty/i18n/vi.po
  addons/pos_discount/i18n/vi.po
  addons/pos_epson_printer/i18n/vi.po
  addons/pos_epson_printer_restaurant/i18n/vi.po
  addons/pos_hr/i18n/vi.po
  addons/pos_loyalty/i18n/vi.po
  addons/pos_restaurant/i18n/vi.po
  addons/product/i18n/vi.po
  addons/spreadsheet_dashboard_pos_hr/i18n/vi.po
Labels: :rocket: Queue

#629 [I18N] [16.0] hr_holidays: add translation
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Running
