Repository Viindoo/odoo, pull requests merged in 2023-01, with the labels that each got.

#575 [I18N][14.0] purchase_requisition: edit file translate
  addons/purchase_requisition/i18n/vi.po
Labels: :rocket: Running

#602 [I18N] [15.0] purchase_requisition: update translate
  addons/purchase_requisition/i18n/vi.po
Labels: :rocket: Building, :warning: Failed

#605 [I18N] [14.0] hr_presense: edit translation
  addons/hr_presence/i18n/vi.po
Labels: :rocket: Queue

#609 [I18N] [15.0] hr_presense: edit translation
  addons/hr_presence/i18n/vi.po
Labels: :rocket: Queue

#612 [I18N][15.0] stock translation report deliveryslip
  addons/stock/i18n/vi.po
Labels: :rocket: Building, :warning: Failed
