Repository Viindoo/odoo, pull requests merged in 2023-05, with the labels that each got.

#670 [MISC] adjust manifest template for Viindoo's conventions
  odoo/cli/templates/default/__manifest__.py.template
Labels: :warning: Failed

#673 [I18N]pos_discount: remove conflict i18n vi.po
  addons/pos_discount/i18n/vi.po
Labels: :rocket: Building

#675 Merged from upstream 13 230517 01
  odoo/modules/module.py
  odoo/tools/cloc.py
Labels: :rocket: Running
