Repository Viindoo/odoo, pull requests merged in 2023-10, with the labels that each got.

#781 Merge from upstream 16 20231013
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/auth_ldap/i18n/vi.po
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/account_journal_dashboard.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/iap/data/neutralize.sql
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/loyalty/tests/test_loyalty.py
  addons/loyalty/views/loyalty_reward_views.xml
  addons/note/views/note_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/spreadsheet/static/src/chart/odoo_chart/odoo_line_chart.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  doc/cla/individual/mikolodz.md
Labels: :rocket: Running

#784 [I18N] [16.0] crm: imp trans
  addons/crm/i18n/vi.po
Labels: :rocket: Queue

#782 [I18N] [16.0] hr_holiday: imp trans
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Running

#788 Merged from upstream 13 231019 01
  odoo/modules/module.py
Labels: :rocket: Running

#793 Merged from upstream 16 231023 01
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/base_vat/models/res_partner.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hw_drivers/event_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008_purchase/models/purchase.py
  addons/l10n_din5008_sale/models/sale.py
  addons/l10n_din5008_stock/models/stock.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/mrp/tests/test_order.py
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move.py
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_ui.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web/static/tests/views/view_dialogs/export_data_dialog_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/models/website_visitor.py
  addons/website_crm/models/website_visitor.py
  addons/website_crm_partner_assign/data/mail_template_data.xml
  addons/website_crm_partner_assign/i18n/website_crm_partner_assign.pot
  addons/website_event/views/website_visitor_views.xml
  addons/website_event_track/views/website_visitor_views.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/tests/test_website_sale_cart.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_binary.py
  odoo/addons/test_http/tests/test_static.py
Labels: :rocket: Running

#785 [I18N] [16.0] sale: imp trans
  addons/sale/i18n/vi.po
Labels: :warning: Failed

#792 [I18N] [16.0] mass_mailing_themes: imp trans
  addons/mass_mailing_themes/i18n/vi.po
Labels: :rocket: Running

#783 [I18N] [16.0] account_edi: imp trans
  addons/account_edi/i18n/vi.po
Labels: :warning: Failed

#779 [I18N] [16.0] website_slide: imp translation
  addons/website_slides/i18n/vi.po
Labels: :warning: Failed
