Repository Viindoo/odoo, pull requests merged in 2024-06, with the labels that each got.

#913 Merged from upstream 15 240604 01
  addons/l10n_eg_edi_eta/views/product_template_views.xml
  addons/l10n_it_edi/models/res_company.py
  addons/survey/static/src/js/survey_session_chart.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  odoo/addons/base/data/res_users_demo.xml
Labels: :rocket: Running

#916 [I18N] [16.0] calendar: improve trans mail template
  addons/calendar/i18n/vi.po
Labels: :rocket: Queue

#920 [I18N] account: correct translations
  addons/account/i18n/vi.po
Labels: :rocket: Building

#921 [I18N] account, base: correct translations
  addons/account/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Building

#922 [I18N] hr_holidays: update translate
  addons/hr_holidays/i18n/vi.po
Labels: :rocket: Building
