Repository Viindoo/odoo, pull requests merged in 2024-10, with the labels that each got.

#995 [I18N][14.0] fleet: Improve Vietnamese translation
  addons/fleet/i18n/vi.po
Labels: :warning: Failed

#1008 [FIX] coupon: change the translation of `Validity` from `Ngày xác nhận` to `Có hiệu lực đến`
  addons/coupon/i18n/vi.po
Labels: :rocket: Queue

#1010 [I18N] *: update translation for mail.template
  addons/auth_signup/i18n/vi.po
  addons/crm_iap_mine/i18n/vi.po
  addons/gamification/i18n/vi.po
  addons/lunch/i18n/vi.po
  addons/portal/i18n/vi.po
  addons/project/i18n/vi.po
  addons/purchase/i18n/vi.po
  addons/repair/i18n/vi.po
  addons/survey/i18n/vi.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_profile/i18n/vi.po
  addons/website_slides/i18n/vi.po
Labels: :rocket: Running

#1011 [FIX] mrp: avoid traceback when leave_id on workorders is not set
  addons/mrp/models/mrp_production.py
Labels: :rocket: Queue

#1013 Merge from upstream 15 20241016 01
  addons/account/models/account_journal.py
  addons/base_vat/models/res_partner.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/sale_project/views/project_sharing_views.xml
  addons/sale_project/views/project_task_views.xml
  addons/website_slides/views/website_slides_templates_profile.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_ir_mail_server.py
Labels: :rocket: Building

#1014 [I18N] stock_landed_costs: missing space
  addons/stock_landed_costs/i18n/vi.po
Labels: :rocket: Queue

#1016 [I18N] base: improve Vietnamese translations
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Queue

#1018 [I18N][17.0] survey: slightly improve translation in certification
  addons/survey/i18n/vi.po
Labels: :rocket: Running

#1019 [I18N] point_of_sale: improve Vietnamese translation
  addons/point_of_sale/i18n/vi.po
Labels: :rocket: Queue

#1022 Merge from upstream 14 20241025 01
  addons/account/tests/test_account_move_out_invoice.py
Labels: :rocket: Running

#1025 [I18N] account: retain English for the Incoterm
  addons/account/i18n/vi.po
Labels: :rocket: Queue
