Repository Viindoo/odoo, pull requests merged in 2024-01, with the labels that each got.

#832 [I18N] [16.0] website_slides: improve trans
  addons/website_slides/i18n/vi.po
Labels: :rocket: Queue

#828 [14.0][I18N] website_sale: revise terminology
  addons/website_sale/i18n/vi.po
Labels: :rocket: Running

#829 [15.0][I18N] website_sale: revise terminology
  addons/website_sale/i18n/vi.po
Labels: :rocket: Running

#834 [IMP][16.0] test_lint: Add support for ES11 (ECMAScript 2020)
  odoo/addons/test_lint/tests/eslintrc
  odoo/addons/test_lint/tests/test_ecmascript.py
Labels: :rocket: Running

#838 [I18N][16.0] crm: translate term lead
  addons/crm/i18n/vi.po
Labels: :rocket: Building

#836 [I18N+FIX][16.0] base_setup: improve translate help fix weird error
  addons/base_setup/i18n/vi.po
Labels: :rocket: Running
