Repository Viindoo/odoo, pull requests merged in 2024-11, with the labels that each got.

#1027 Merge from upstream 15 20241102 01
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: :rocket: Running

#1030 [FIX] base, hr_holidays: TypeError: not enough arguments for format string
  odoo/addons/base/i18n/et.po
Labels: :rocket: Building

#1032 [I18N] account: fix typo `nút toán` -> `bút toán`
  addons/account/i18n/vi.po
Labels: :rocket: Queue

#1036 [I18N][15.0] repair: update translate
  addons/repair/i18n/vi.po
Labels: :rocket: Queue

#1035 [I18N][17.0] repair: update translate
  addons/repair/i18n/vi.po
Labels: :rocket: Building

#1037 [i18N][16.0] repair: update translate
  addons/repair/i18n/vi.po
Labels: :rocket: Queue

#1039 [I18N] base_import: correct Vietnamese translation
  addons/base_import/i18n/vi.po
Labels: :rocket: Queue

#1043 [FIX] *: test pylint `%s`
  addons/base_import/i18n/hr.po
  addons/hr_holidays/i18n/fa.po
  addons/im_livechat/i18n/lv.po
  addons/loyalty/i18n/fa.po
  addons/mrp/i18n/fa.po
  addons/mrp_account/i18n/fa.po
  addons/purchase/i18n/hr.po
  addons/repair/i18n/fa.po
  addons/spreadsheet/i18n/pl.po
  addons/web/i18n/fa.po
  addons/web_editor/i18n/fa.po
  odoo/addons/base/i18n/et.po
Labels: :rocket: Queue

#1044 [I18N] *: Fix pylint
  addons/im_livechat/i18n/lv.po
  addons/loyalty/i18n/fa.po
  addons/mail/i18n/fa.po
  addons/mrp/i18n/fa.po
  addons/mrp_account/i18n/fa.po
  addons/stock/i18n/fa.po
Labels: :rocket: Building

#1046 Merge from upstream 16 20241130 01
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_nlcius.py
  addons/account_edi_ubl_cii_tax_extension/tests/test_ubl_cii_tax_extension.py
  addons/analytic/models/analytic_account.py
  addons/crm/models/crm_lead.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/mail/models/ir_attachment.py
  addons/mail/models/mail_message.py
  addons/mail/tests/test_res_users.py
  addons/mail/tests/test_user_modify_own_profile.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/tests/tours/helpers/PaymentScreenTourMethods.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/models/product_category.py
  addons/project/models/project.py
  addons/project/tests/test_portal.py
  addons/project/tests/test_project_sharing_portal_access.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/rating/controllers/main.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_account/tests/test_account_move.py
  addons/test_mail/models/__init__.py
  addons/test_mail/models/mail_test_access.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_form_project/tests/test_project_portal_access.py
  doc/cla/corporate/xcellentexchange.md
  setup/win32/setup.nsi
Labels: :rocket: Running
