Repository Viindoo/odoo, pull requests merged in 2024-12, with the labels that each got.

#1047 [I18N] sale: correct translations
  addons/sale/i18n/vi.po
Labels: :rocket: Queue

#1051 [FIX][16.0] website_sale: fix pylint
  addons/website_sale/i18n/az.po
Labels: :rocket: Building

#1052 [FIX] point_of_sale: allow cashiers to close sessions without accounting's Administrator access rights
  addons/point_of_sale/models/pos_session.py
Labels: :rocket: Building

#1055 [I18N] purchase: missing spacing
  addons/purchase/i18n/vi.po
Labels: :rocket: Queue

#1058 [IMP][17.0] base: add migration script to update currency rate rule
  odoo/addons/base/__manifest__.py
  odoo/addons/base/migrations/17.0.1.4/post-migration.py
Labels: :rocket: Running

#1060 [I18N] *: fix format string
  addons/account/i18n/ar.po
  addons/account/i18n/hr.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/base_import/i18n/hr.po
  addons/event/i18n/ro.po
  addons/gamification/i18n/ru.po
  addons/im_livechat/i18n/lv.po
  addons/loyalty/i18n/ru.po
  addons/mail/i18n/fi.po
  addons/mail/i18n/ro.po
  addons/mail/i18n/th.po
  addons/payment_worldline/i18n/pt_BR.po
  addons/pos_event/i18n/th.po
  addons/product/i18n/et.po
  addons/project/i18n/pl.po
  addons/purchase/i18n/et.po
  addons/purchase/i18n/hr.po
  addons/purchase/i18n/ja.po
  addons/spreadsheet/i18n/es.po
  addons/spreadsheet/i18n/es_419.po
  addons/spreadsheet/i18n/pl.po
  addons/stock/i18n/et.po
  addons/web/i18n/az.po
  addons/web/i18n/et.po
  addons/website/i18n/ja.po
  addons/website_hr_recruitment/i18n/ru.po
  addons/website_sale/i18n/pt.po
  odoo/addons/base/i18n/az.po
  odoo/addons/base/i18n/et.po
Labels: :rocket: Queue
