Repository Viindoo/odoo, pull requests merged in 2024-09, with the labels that each got.

#962 [15.0][I18N] mrp: correct spelling
  addons/mrp/i18n/vi.po
Labels: :rocket: Running

#952 [FIX][16.0] account: wrong translation placeholder
  addons/account/i18n/vi.po
Labels: :rocket: Running

#951 [FIX][17.0] account: wrong translation placeholder
  addons/account/i18n/vi.po
Labels: :rocket: Running

#972 [I18N] *: fix typo: `& amp;` -> `&amp;`
  addons/account/i18n/bn.po
  addons/account/i18n/cs.po
  addons/account/i18n/de.po
  addons/account/i18n/sk.po
  addons/event/i18n/da.po
  addons/event/i18n/tr.po
  addons/event/i18n/vi.po
  addons/point_of_sale/i18n/ro.po
  addons/project/i18n/sk.po
  addons/sale/i18n/cs.po
  addons/sale/i18n/lv.po
  addons/stock/i18n/pt_BR.po
  addons/stock/i18n/tr.po
  addons/stock_account/i18n/tr.po
  addons/website/i18n/az.po
  addons/website/i18n/bn.po
  addons/website/i18n/cs.po
  addons/website_event/i18n/tr.po
  addons/website_sale/i18n/ro.po
  addons/website_slides/i18n/sk.po
  addons/website_slides/i18n/tr.po
Labels: :rocket: Queue

#973 [I18N] *: fix typo: `& amp;` -> `&amp;`
  addons/account/i18n/de.po
  addons/account/i18n/km.po
  addons/account/i18n/sk.po
  addons/event/i18n/da.po
  addons/event/i18n/km.po
  addons/event/i18n/tr.po
  addons/event/i18n/vi.po
  addons/project/i18n/sk.po
  addons/purchase/i18n/km.po
  addons/sale/i18n/km.po
  addons/sale/i18n/lv.po
  addons/sale_quotation_builder/i18n/km.po
  addons/sale_stock/i18n/km.po
  addons/stock/i18n/pt_BR.po
  addons/stock/i18n/tr.po
  addons/stock_account/i18n/tr.po
  addons/website/i18n/az.po
  addons/website/i18n/km.po
  addons/website_event/i18n/km.po
  addons/website_slides/i18n/sk.po
  addons/website_slides/i18n/tr.po
  odoo/addons/base/i18n/km.po
Labels: :rocket: Queue

#974 [I18N] *: fix typo: `& amp;` -> `&amp;`
  addons/account/i18n/lv.po
  addons/event/i18n/da.po
  addons/event/i18n/tr.po
  addons/portal/i18n/ro.po
  addons/project/i18n/sk.po
  addons/sale/i18n/lv.po
  addons/website/i18n/az.po
  addons/website_slides/i18n/sk.po
  addons/website_slides/i18n/tr.po
Labels: :rocket: Queue

#979 [I18N] *: change the translation of `Archived` from `Đã lưu` to `Đã lưu trữ`
  addons/event_booth/i18n/vi.po
  addons/im_livechat/i18n/vi.po
  addons/loyalty/i18n/vi.po
  addons/privacy_lookup/i18n/vi.po
  addons/purchase_requisition/i18n/vi.po
  addons/website_crm_iap_reveal/i18n/vi.po
  addons/website_event_exhibitor/i18n/vi.po
Labels: :rocket: Queue

#959 [14.0][I18N] event: translate missing word
  addons/event/i18n/vi.po
  addons/event_sms/i18n/vi.po
Labels: :rocket: Running

#965 [14.0][I18N] mrp: translate missing vietnamese word
  addons/mrp/i18n/vi.po
Labels: :rocket: Running

#984 [16.0][I18N] hr_recruitment_skills: translate vietnamese term
  addons/hr_recruitment_skills/i18n/vi.po
Labels: :rocket: Running

#950 [16.0][I18N] fleet: translate for all vehicles access group
  addons/fleet/i18n/vi.po
Labels: :rocket: Running

#982 [16.0][I18N] sale_purchase: Correct Vietnamese terms to fit the context
  addons/sale_purchase/i18n/vi.po
Labels: :rocket: Running

#983 [I18N] [16.0] website_hr_recruitment: update translate
  addons/website_hr_recruitment/i18n/vi.po
Labels: :rocket: Queue

#953 [16.0][I18N] calendar - data_recyccle: translate some missing texts
  addons/calendar/i18n/vi.po
  addons/data_recycle/i18n/vi.po
Labels: :rocket: Queue

#954 [15.0][I18N] calendar: correct Vietnamese translation
  addons/calendar/i18n/vi.po
Labels: :rocket: Building

#955 [17.0][I18N] calendar - data_recycle: correct Vietnamese Translation
  addons/calendar/i18n/vi.po
  addons/data_recycle/i18n/vi.po
Labels: :rocket: Running

#960 [15.0][I18N] event: inappropriate terminology translation
  addons/event/i18n/vi.po
Labels: :rocket: Running

#961 [16.0][I18N] event: inappropriate terminology translation
  addons/event/i18n/vi.po
Labels: :rocket: Running

#990 [I18N][16.0] stock: update translate
  addons/stock/i18n/vi.po
Labels: :rocket: Queue

#981 [I18N][16.0] account*: fix i18n
  addons/account/i18n/vi.po
  addons/iap/i18n/vi.po
  addons/snailmail/i18n/vi.po
Labels: :rocket: Queue

#830 [16.0][I18N] website_sale: revise terminology
  addons/loyalty/i18n/vi.po
  addons/website_sale/i18n/vi.po
Labels: :rocket: Queue

#958 [I18N] [15.0] resource: update translate
  addons/resource/i18n/vi.po
Labels: :rocket: Queue

#969 [16.0][I18N] *: correct vietnamese terminology for warehouse module cluster
  addons/purchase_stock/i18n/vi.po
  addons/sale_stock/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: :rocket: Queue

#957 [I18N] [16.0] resource: update translate
  addons/hr_holidays/i18n/vi.po
  addons/resource/i18n/vi.po
Labels: :rocket: Queue

#956 [I18N] [17.0] resource: update translate
  addons/hr_holidays/i18n/vi.po
  addons/resource/i18n/vi.po
Labels: :rocket: Queue

#991 [16.0][I18N] hr_recruimtment_skills: translate some missing Vietnamese terms
  addons/hr_recruitment_skills/i18n/vi.po
Labels: :rocket: Queue

#970 [16.0][I18N] *: Add untranslated Vietnamese term for services cluster
  addons/hr_timesheet/i18n/vi.po
  addons/project/i18n/vi.po
Labels: :rocket: Queue

#980 [I18N][16.0] *pos: fix i18n
  addons/point_of_sale/i18n/vi.po
Labels: :rocket: Queue

#993 Merge from upstream 16 20240925 01
  addons/account/models/account_payment.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/l10n_es/__init__.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/l10n_es/migrations/5.3/post-migrate_update_taxes.py
  addons/mail/static/src/components/message/message.scss
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/report/report_deliveryslip.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/models/stock_rule.py
  addons/resource/models/resource.py
  addons/sale/views/sale_portal_templates.xml
  addons/sale_purchase_stock/tests/test_access_rights.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website_event/i18n/website_event.pot
  addons/website_event/views/event_templates_list.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/security/base_groups.xml
Labels: :rocket: Running

#994 Merge from upstream 17 20240925 01
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account_payment_term/models/account_payment_term.py
  addons/hr/models/hr_employee_base.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/hr_employee_base.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_it_edi_withholding/data/template/account.account-it.csv
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/data/template/account.tax.group-it.csv
  addons/l10n_pe/data/template/account.tax-pe.csv
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message.scss
  addons/mrp/report/mrp_report_bom_structure.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/reprint_receipt_screen.js
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/purchase_stock/models/stock_move.py
  addons/resource/models/resource_calendar.py
  addons/sale/views/sale_portal_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_searchbar/000.xml
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_customer/views/website_customer_templates.xml
  addons/website_event/views/event_templates_list.xml
  addons/website_forum/views/forum_forum_templates_post.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_loyalty/static/src/js/website_sale_loyalty_delivery.js
  addons/website_sale_loyalty/static/tests/tours/test_website_sale_free_shipping_discount_line.js
  addons/website_sale_loyalty/tests/test_website_sale_loyalty_delivery.py
  odoo/addons/base/security/base_groups.xml
  odoo/tools/mail.py
Labels: :rocket: Running

#998 [I18N] *: avoid TypeError
  addons/account/i18n/de.po
  addons/auth_signup/i18n/km.po
  addons/crm/i18n/cs.po
  addons/mrp/i18n/vi.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/tr.po
  addons/purchase/i18n/pl.po
  addons/sale_timesheet/i18n/vi.po
  addons/stock/i18n/ca.po
  addons/stock/i18n/hu.po
  addons/stock_landed_costs/i18n/vi.po
  addons/survey/i18n/ko.po
  addons/web/i18n/es_CO.po
  addons/website_blog/i18n/es_CO.po
  addons/website_blog/i18n/es_EC.po
  addons/website_blog/i18n/kab.po
  addons/website_forum/i18n/vi.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/lv.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/th.po
Labels: :warning: Failed

#996 Merge from upstream 17 20240926 01
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_jo/data/template/account.tax-jo_standard.csv
  addons/l10n_jo/data/template/account.tax.group-jo_standard.csv
  addons/mrp/report/report_deliveryslip.xml
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/purchase_stock/models/stock_rule.py
  addons/sale_purchase_stock/tests/test_access_rights.py
  addons/website/models/website_page.py
  addons/website/tests/test_page.py
  addons/website_sale/static/src/js/website_sale_delivery.js
  addons/website_sale/static/tests/tours/website_free_delivery.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_actions_report.py
Labels: :rocket: Running

#1000 [I18N] *: avoid TypeError
  addons/account/i18n/az.po
  addons/account/i18n/de.po
  addons/account_edi_proxy_client/i18n/zh_TW.po
  addons/base_import/i18n/az.po
  addons/coupon/i18n/fr.po
  addons/event/i18n/ro.po
  addons/gamification/i18n/ca.po
  addons/hr_holidays/i18n/vi.po
  addons/mail/i18n/ro.po
  addons/point_of_sale/i18n/ca.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/tr.po
  addons/purchase/i18n/pl.po
  addons/sale_timesheet/i18n/vi.po
  addons/stock/i18n/hu.po
  addons/stock_landed_costs/i18n/vi.po
  addons/web/i18n/az.po
  addons/web/i18n/es_CO.po
  addons/website/i18n/az.po
  addons/website_blog/i18n/bg.po
  addons/website_blog/i18n/es_CO.po
  addons/website_blog/i18n/es_EC.po
  addons/website_blog/i18n/kab.po
  addons/website_forum/i18n/vi.po
  addons/website_sale/i18n/fa.po
  addons/website_sale/i18n/it.po
  addons/website_sale/i18n/pt.po
  addons/website_sale_stock/i18n/az.po
  odoo/addons/base/i18n/az.po
  odoo/addons/base/i18n/lv.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/th.po
  odoo/addons/base/i18n/tr.po
Labels: :rocket: Running

#1001 [I18N] *: avoid TypeError
  addons/base_import/i18n/az.po
  addons/coupon/i18n/vi.po
  addons/event/i18n/de.po
  addons/event/i18n/ro.po
  addons/hr_holidays_attendance/i18n/vi.po
  addons/l10n_latam_check/i18n/es.po
  addons/loyalty/i18n/ru.po
  addons/mail/i18n/fi.po
  addons/mail/i18n/ro.po
  addons/point_of_sale/i18n/ca.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/tr.po
  addons/web/i18n/az.po
  addons/web/i18n/es_CO.po
  addons/website_blog/i18n/es_CO.po
  addons/website_blog/i18n/es_EC.po
  addons/website_blog/i18n/kab.po
  addons/website_forum/i18n/vi.po
  addons/website_sale/i18n/fa.po
  odoo/addons/base/i18n/az.po
  odoo/addons/base/i18n/lv.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/th.po
  odoo/addons/base/i18n/uk.po
Labels: :rocket: Running

#1002 [I18N] *: avoid TypeError
  addons/account/i18n/fa.po
  addons/base_import/i18n/az.po
  addons/event/i18n/ro.po
  addons/gamification/i18n/ru.po
  addons/hr_holidays_attendance/i18n/vi.po
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_latam_check/i18n/es_419.po
  addons/loyalty/i18n/ru.po
  addons/mail/i18n/fi.po
  addons/mrp/i18n/az.po
  addons/point_of_sale/i18n/ca.po
  addons/point_of_sale/i18n/tr.po
  addons/purchase_requisition/i18n/ru.po
  addons/web/i18n/az.po
  addons/website_forum/i18n/vi.po
  addons/website_hr_recruitment/i18n/ru.po
  addons/website_sale/i18n/fa.po
  odoo/addons/base/i18n/az.po
  odoo/addons/base/i18n/mn.po
Labels: :rocket: Running

#1003 Merge from upstream 16 20240928 01
  addons/account/__init__.py
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/account/models/partner.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_fiscal_position.py
  addons/hr_expense/static/src/components/expense_dashboard.js
  addons/l10n_se/__manifest__.py
  addons/l10n_se/data/account_tax_report_data.xml
  addons/l10n_se/data/account_tax_template.xml
  addons/l10n_se/migrations/1.1/end-migrate.py
  addons/microsoft_calendar/tests/test_microsoft_service.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/project/wizard/project_task_type_delete.py
  addons/sale_stock/tests/test_create_perf.py
  addons/stock/models/stock_quant.py
  addons/stock/wizard/stock_request_count.py
  addons/stock_account/models/account_chart_template.py
  addons/stock_account/models/product.py
  addons/web/static/src/search/search_panel/search_panel.xml
  addons/web_editor/static/src/js/frontend/loader.js
  addons/website/models/website_page.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_profile/__manifest__.py
  addons/website_profile/models/res_users.py
  addons/website_profile/static/src/js/website_profile.js
  addons/website_profile/static/tests/tours/tour_website_profile_description.js
  addons/website_profile/tests/__init__.py
  addons/website_profile/tests/test_website_profile.py
Labels: :rocket: Running
