Repository Viindoo/odoo, pull requests merged in 2025-08, with the labels that each got.

#1123 [16.0][I18N] website_sale: Add some missing translations
  addons/website_sale/i18n/vi.po
Labels: :rocket: Building

#1106 [I18N][16.0] stock: correct Vietnamese translation in stock
  addons/stock/i18n/vi.po
Labels: :rocket: Queue

#1129 [I18N][17.0] hr_holidays: update translate vi_VN
  addons/hr_holidays/i18n/vi.po
Labels: :warning: Failed
